### ISSUE TITLE
Biome features spawning in water

### ISSUE THREAD

**Issue by TheMagicalSC** [KaboomRoads/LostFeatures#12]
![2024-07-05_15 20 16](https://github.com/user-attachments/assets/346cf22e-0e45-48c2-933f-1cb1c84b73e1)
![2024-07-05_15 20 13](https://github.com/user-attachments/assets/fa589fae-0e2c-4338-a1db-7417c3902d01)

**Comment by KaboomRoads** [comment]
should be fixed in the next version
