### ISSUE TITLE
Unknown type 'minecraft:alternative' (baobab_leaves loot tables)

### ISSUE THREAD

**Issue by XspeedPL** [KaboomRoads/LostFeatures#9]
The condition type "minecraft:alternative" has been replaced by "minecraft:any_of" in Minecraft 1.20+

https://github.com/KaboomRoads/LostFeatures/blob/014e2cf88b177101d82618d787694d86e11d54c5/Common/src/main/resources/data/lostfeatures/loot_tables/blocks/baobab_leaves.json#L14

https://github.com/KaboomRoads/LostFeatures/blob/014e2cf88b177101d82618d787694d86e11d54c5/Common/src/main/resources/data/lostfeatures/loot_tables/blocks/baobab_leaves.json#L72

**Comment by KaboomRoads** [comment]
should be fixed in the next version
